name: banca_creditos
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  circular_gradient_spinner: ^0.0.3
  supabase_flutter: ^2.5.9
  flutter_story_presenter: ^0.0.8 
  excel: ^4.0.3
  path_provider: ^2.1.3
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSansRegular.ttf
  
